# Site settings
title: James Blog
SEOTitle: 桔子的桔子的博客 | James Blog
header-img: img/home-bg.jpg
email: aiyoagan@gmail.com
description: "一个写php的桔子 | 仅此而已"
keyword: "桔子的桔子的博客, James Blog, 博客, 个人网站, 互联网, 后端"
url: "http://www.juzi89.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     agan1989
zhihu_username:     aiyoagan
github_username:    aiyoagan
#twitter_username:  aiyoagan
facebook_username:  juzi89
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
#gems: [jekyll-paginate]
gem 'jekyll-paginate', group: :jekyll_plugins



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: aiyoagan
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: juzi89.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "世界那么大，我想到处看看。"
sidebar-avatar: /img/avatar-juzi.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "桔子的桔子",
        href: "http://www.juzi89.com/"
    }
]
